project_id = "lpwtihfypaajwymgbkko"

[functions.zarinpal-request]
verify_jwt = false

[functions.zarinpal-verify]
verify_jwt = false

[functions.torob-feed]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false
